# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\barium133\Code\barium\lib\clients\gui\HP6033A_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class HP6033A_UI(QtGui.QWidget):
    def setupUi(self):
        Form = self
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(400, 300)
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.ps_current_lcd = QtGui.QLCDNumber(self.frame)
        self.ps_current_lcd.setGeometry(QtCore.QRect(130, 251, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ps_current_lcd.setFont(font)
        self.ps_current_lcd.setObjectName(_fromUtf8("ps_current_lcd"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(130, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.ps_voltage_lcd = QtGui.QLCDNumber(self.frame)
        self.ps_voltage_lcd.setGeometry(QtCore.QRect(10, 250, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ps_voltage_lcd.setFont(font)
        self.ps_voltage_lcd.setObjectName(_fromUtf8("ps_voltage_lcd"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 225, 111, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.ps_voltage_spinbox = QtGui.QDoubleSpinBox(self.frame)
        self.ps_voltage_spinbox.setGeometry(QtCore.QRect(10, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ps_voltage_spinbox.setFont(font)
        self.ps_voltage_spinbox.setObjectName(_fromUtf8("ps_voltage_spinbox"))
        self.ps_voltage_spinbox.setRange(0,3)
        self.ps_current_spinbox = QtGui.QDoubleSpinBox(self.frame)
        self.ps_current_spinbox.setGeometry(QtCore.QRect(130, 180, 111, 31))
        self.ps_current_spinbox.setRange(0,15)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ps_current_spinbox.setFont(font)
        self.ps_current_spinbox.setObjectName(_fromUtf8("ps_current_spinbox"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(130, 160, 91, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.ps_pulse_time_spinbox = QtGui.QDoubleSpinBox(self.frame)
        self.ps_pulse_time_spinbox.setEnabled(False)
        self.ps_pulse_time_spinbox.setGeometry(QtCore.QRect(100, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ps_pulse_time_spinbox.setFont(font)
        self.ps_pulse_time_spinbox.setObjectName(_fromUtf8("ps_pulse_time_spinbox"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ps_pulse_mode_checkbox = QtGui.QCheckBox(self.frame)
        self.ps_pulse_mode_checkbox.setGeometry(QtCore.QRect(190, 40, 81, 21))
        self.ps_pulse_mode_checkbox.setObjectName(_fromUtf8("ps_pulse_mode_checkbox"))
        self.ps_output_checkbox = QtGui.QCheckBox(self.frame)
        self.ps_output_checkbox.setGeometry(QtCore.QRect(260, 240, 111, 31))
        self.ps_output_checkbox.setCheckable(True)
        self.ps_output_checkbox.setChecked(True)
        self.ps_output_checkbox.setTristate(False)
        self.ps_output_checkbox.setObjectName(_fromUtf8("ps_output_checkbox"))
        self.ps_pulse_voltage_button = QtGui.QPushButton(self.frame)
        self.ps_pulse_voltage_button.setEnabled(False)
        self.ps_pulse_voltage_button.setGeometry(QtCore.QRect(180, 110, 111, 41))
        self.ps_pulse_voltage_button.setObjectName(_fromUtf8("ps_pulse_voltage_button"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.ps_pulse_current_spinbox = QtGui.QDoubleSpinBox(self.frame)
        self.ps_pulse_current_spinbox.setEnabled(False)
        self.ps_pulse_current_spinbox.setGeometry(QtCore.QRect(100, 80, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ps_pulse_current_spinbox.setFont(font)
        self.ps_pulse_current_spinbox.setObjectName(_fromUtf8("ps_pulse_current_spinbox"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ps_pulse_current_button = QtGui.QPushButton(self.frame)
        self.ps_pulse_current_button.setEnabled(False)
        self.ps_pulse_current_button.setGeometry(QtCore.QRect(180, 70, 111, 41))
        self.ps_pulse_current_button.setObjectName(_fromUtf8("ps_pulse_current_button"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 91, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ps_pulse_voltage_spinbox = QtGui.QDoubleSpinBox(self.frame)
        self.ps_pulse_voltage_spinbox.setEnabled(False)
        self.ps_pulse_voltage_spinbox.setGeometry(QtCore.QRect(100, 120, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ps_pulse_voltage_spinbox.setFont(font)
        self.ps_pulse_voltage_spinbox.setObjectName(_fromUtf8("ps_pulse_voltage_spinbox"))
        self.ps_set_safety_limits_button = QtGui.QPushButton(self.frame)
        self.ps_set_safety_limits_button.setGeometry(QtCore.QRect(180, 10, 191, 23))
        self.ps_set_safety_limits_button.setObjectName(_fromUtf8("ps_set_safety_limits_button"))
        self.ps_apply_settings_button = QtGui.QPushButton(self.frame)
        self.ps_apply_settings_button.setGeometry(QtCore.QRect(250, 170, 121, 51))
        self.ps_apply_settings_button.setObjectName(_fromUtf8("ps_apply_settings_button"))
        self.ps_mode_text = QtGui.QLineEdit(self.frame)
        self.ps_mode_text.setGeometry(QtCore.QRect(310, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ps_mode_text.setFont(font)
        self.ps_mode_text.setText(_fromUtf8(""))
        self.ps_mode_text.setReadOnly(True)
        self.ps_mode_text.setObjectName(_fromUtf8("ps_mode_text"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(310, 90, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))

        self.retranslateUi()
        QtCore.QObject.connect(self.ps_pulse_mode_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ps_pulse_voltage_button.setEnabled)
        QtCore.QObject.connect(self.ps_pulse_mode_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ps_pulse_time_spinbox.setEnabled)
        QtCore.QObject.connect(self.ps_pulse_mode_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ps_pulse_current_spinbox.setEnabled)
        QtCore.QObject.connect(self.ps_pulse_mode_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ps_current_spinbox.setDisabled)
        QtCore.QObject.connect(self.ps_pulse_mode_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ps_voltage_spinbox.setDisabled)
        QtCore.QObject.connect(self.ps_pulse_mode_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ps_pulse_current_button.setEnabled)
        QtCore.QObject.connect(self.ps_pulse_mode_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ps_pulse_voltage_spinbox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self):
        Form = self
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_5.setText(_translate("Form", "Measured Current (V)", None))
        self.label_4.setText(_translate("Form", "Measured Voltage (V)", None))
        self.label.setText(_translate("Form", "Set Voltage (V)", None))
        self.label_3.setText(_translate("Form", "Set Current (A)", None))
        self.label_2.setText(_translate("Form", "Pulse Time (s)", None))
        self.ps_pulse_mode_checkbox.setText(_translate("Form", "Pulse Mode", None))
        self.ps_output_checkbox.setText(_translate("Form", "Output State", None))
        self.ps_pulse_voltage_button.setText(_translate("Form", "Pulse Voltage", None))
        self.label_6.setText(_translate("Form", "Power Supply", None))
        self.label_7.setText(_translate("Form", "Pulse Current (A)", None))
        self.ps_pulse_current_button.setText(_translate("Form", "Pulse Current", None))
        self.label_8.setText(_translate("Form", "Pulse Voltage (V)", None))
        self.ps_set_safety_limits_button.setText(_translate("Form", "Set Safety Limits ...", None))
        self.ps_apply_settings_button.setText(_translate("Form", "Apply Settings", None))
        self.label_9.setText(_translate("Form", "Mode", None))

