# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\barium133\Code\barium\lib\clients\gui\MassSpecExperiment_II_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(800, 600)
        self.frame_1 = QtGui.QFrame(Form)
        self.frame_1.setGeometry(QtCore.QRect(10, 100, 541, 491))
        self.frame_1.setFrameShape(QtGui.QFrame.Panel)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.delete_button = QtGui.QPushButton(self.frame_1)
        self.delete_button.setGeometry(QtCore.QRect(10, 360, 131, 31))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.save_button = QtGui.QPushButton(self.frame_1)
        self.save_button.setGeometry(QtCore.QRect(130, 440, 121, 31))
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.load_button = QtGui.QPushButton(self.frame_1)
        self.load_button.setGeometry(QtCore.QRect(10, 440, 121, 31))
        self.load_button.setObjectName(_fromUtf8("load_button"))
        self.experiment_tree = QtGui.QTreeWidget(self.frame_1)
        self.experiment_tree.setGeometry(QtCore.QRect(260, 10, 271, 471))
        self.experiment_tree.setObjectName(_fromUtf8("experiment_tree"))
        item_0 = QtGui.QTreeWidgetItem(self.experiment_tree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.experiment_tree)
        self.add_new_datarun_button = QtGui.QPushButton(self.frame_1)
        self.add_new_datarun_button.setGeometry(QtCore.QRect(10, 10, 241, 31))
        self.add_new_datarun_button.setObjectName(_fromUtf8("add_new_datarun_button"))
        self.add_repeat_button = QtGui.QPushButton(self.frame_1)
        self.add_repeat_button.setGeometry(QtCore.QRect(160, 40, 91, 31))
        self.add_repeat_button.setObjectName(_fromUtf8("add_repeat_button"))
        self.add_scan_button = QtGui.QPushButton(self.frame_1)
        self.add_scan_button.setGeometry(QtCore.QRect(10, 290, 241, 31))
        self.add_scan_button.setObjectName(_fromUtf8("add_scan_button"))
        self.scan_table = QtGui.QTableWidget(self.frame_1)
        self.scan_table.setGeometry(QtCore.QRect(10, 80, 241, 211))
        self.scan_table.setObjectName(_fromUtf8("scan_table"))
        self.scan_table.setColumnCount(1)
        self.scan_table.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.scan_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.scan_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.scan_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.scan_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.scan_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.scan_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.scan_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.scan_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.scan_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.scan_table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.scan_table.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.scan_table.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.scan_table.setItem(5, 0, item)
        self.move_up_button = QtGui.QPushButton(self.frame_1)
        self.move_up_button.setGeometry(QtCore.QRect(140, 360, 111, 31))
        self.move_up_button.setObjectName(_fromUtf8("move_up_button"))
        self.move_down_button = QtGui.QPushButton(self.frame_1)
        self.move_down_button.setGeometry(QtCore.QRect(140, 390, 111, 31))
        self.move_down_button.setObjectName(_fromUtf8("move_down_button"))
        self.clear_button = QtGui.QPushButton(self.frame_1)
        self.clear_button.setGeometry(QtCore.QRect(10, 390, 131, 31))
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.repetitions_spinbox = QtGui.QSpinBox(self.frame_1)
        self.repetitions_spinbox.setGeometry(QtCore.QRect(100, 40, 61, 31))
        self.repetitions_spinbox.setMinimum(1)
        self.repetitions_spinbox.setObjectName(_fromUtf8("repetitions_spinbox"))
        self.label_9 = QtGui.QLabel(self.frame_1)
        self.label_9.setGeometry(QtCore.QRect(20, 45, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(560, 112, 231, 481))
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 420, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 360, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.total_experiment_progressbar = QtGui.QProgressBar(self.frame_2)
        self.total_experiment_progressbar.setGeometry(QtCore.QRect(10, 380, 211, 23))
        self.total_experiment_progressbar.setProperty("value", 0)
        self.total_experiment_progressbar.setObjectName(_fromUtf8("total_experiment_progressbar"))
        self.current_scan_progressbar = QtGui.QProgressBar(self.frame_2)
        self.current_scan_progressbar.setGeometry(QtCore.QRect(10, 310, 211, 23))
        self.current_scan_progressbar.setProperty("value", 0)
        self.current_scan_progressbar.setObjectName(_fromUtf8("current_scan_progressbar"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 330, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.abort_button = QtGui.QPushButton(self.frame_2)
        self.abort_button.setGeometry(QtCore.QRect(10, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.abort_button.setFont(font)
        self.abort_button.setObjectName(_fromUtf8("abort_button"))
        self.begin_button = QtGui.QPushButton(self.frame_2)
        self.begin_button.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.begin_button.setFont(font)
        self.begin_button.setObjectName(_fromUtf8("begin_button"))
        self.timer_lcd = QtGui.QLCDNumber(self.frame_2)
        self.timer_lcd.setGeometry(QtCore.QRect(10, 442, 181, 31))
        self.timer_lcd.setObjectName(_fromUtf8("timer_lcd"))
        self.data_button = QtGui.QPushButton(self.frame_2)
        self.data_button.setGeometry(QtCore.QRect(10, 70, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.data_button.setFont(font)
        self.data_button.setObjectName(_fromUtf8("data_button"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 9, 781, 91))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.connect_button = QtGui.QPushButton(self.frame)
        self.connect_button.setGeometry(QtCore.QRect(440, 20, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName(_fromUtf8("connect_button"))
        self.sca_id_spinbox = QtGui.QSpinBox(self.frame)
        self.sca_id_spinbox.setGeometry(QtCore.QRect(360, 60, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sca_id_spinbox.setFont(font)
        self.sca_id_spinbox.setObjectName(_fromUtf8("sca_id_spinbox"))
        self.hp_id_spinbox = QtGui.QSpinBox(self.frame)
        self.hp_id_spinbox.setGeometry(QtCore.QRect(360, 30, 42, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hp_id_spinbox.setFont(font)
        self.hp_id_spinbox.setObjectName(_fromUtf8("hp_id_spinbox"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(170, 60, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(170, 30, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.host_name_combobox = QtGui.QComboBox(self.frame)
        self.host_name_combobox.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.host_name_combobox.setFont(font)
        self.host_name_combobox.setEditable(True)
        self.host_name_combobox.setObjectName(_fromUtf8("host_name_combobox"))
        self.host_name_combobox.addItem(_fromUtf8(""))
        self.host_name_combobox.addItem(_fromUtf8(""))
        self.host_name_combobox.addItem(_fromUtf8(""))
        self.host_name_combobox.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame.raise_()
        self.frame_1.raise_()
        self.frame_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.delete_button.setText(_translate("Form", "(-) Delete Selected Item", None))
        self.save_button.setText(_translate("Form", "Save Experiment ...", None))
        self.load_button.setText(_translate("Form", "Load Experiment ...", None))
        self.experiment_tree.headerItem().setText(0, _translate("Form", "Experiment", None))
        __sortingEnabled = self.experiment_tree.isSortingEnabled()
        self.experiment_tree.setSortingEnabled(False)
        self.experiment_tree.topLevelItem(0).setText(0, _translate("Form", "Sample Datarun [ml,dl,c,fl,hv,rps]", None))
        self.experiment_tree.topLevelItem(0).child(0).setText(0, _translate("Form", "Sample Scan [133,220,13,1,2200,500]", None))
        self.experiment_tree.topLevelItem(1).setText(0, _translate("Form", "Sample Repeat Command [0]", None))
        self.experiment_tree.setSortingEnabled(__sortingEnabled)
        self.add_new_datarun_button.setText(_translate("Form", "(+) Add New Datarun >>>", None))
        self.add_repeat_button.setText(_translate("Form", "(+) Add >>>", None))
        self.add_scan_button.setText(_translate("Form", "(+) Add Scan to selected Datarun >>>", None))
        item = self.scan_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "[ml] Mass (amu)", None))
        item = self.scan_table.verticalHeaderItem(1)
        item.setText(_translate("Form", "[dl] Discriminator Level (V)", None))
        item = self.scan_table.verticalHeaderItem(2)
        item.setText(_translate("Form", "[c] Current (A)", None))
        item = self.scan_table.verticalHeaderItem(3)
        item.setText(_translate("Form", "[fl] RGA Filament (0 or 1)", None))
        item = self.scan_table.verticalHeaderItem(4)
        item.setText(_translate("Form", "[hv] RGA Voltage (V)", None))
        item = self.scan_table.verticalHeaderItem(5)
        item.setText(_translate("Form", "[rps] Records per Scan", None))
        item = self.scan_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Value", None))
        __sortingEnabled = self.scan_table.isSortingEnabled()
        self.scan_table.setSortingEnabled(False)
        item = self.scan_table.item(0, 0)
        item.setText(_translate("Form", "133", None))
        item = self.scan_table.item(1, 0)
        item.setText(_translate("Form", "220", None))
        item = self.scan_table.item(2, 0)
        item.setText(_translate("Form", "13", None))
        item = self.scan_table.item(3, 0)
        item.setText(_translate("Form", "1", None))
        item = self.scan_table.item(4, 0)
        item.setText(_translate("Form", "2200", None))
        item = self.scan_table.item(5, 0)
        item.setText(_translate("Form", "500", None))
        self.scan_table.setSortingEnabled(__sortingEnabled)
        self.move_up_button.setText(_translate("Form", "Move Up", None))
        self.move_down_button.setText(_translate("Form", "Move Down", None))
        self.clear_button.setText(_translate("Form", "(-) Clear Items", None))
        self.label_9.setText(_translate("Form", "Repetitions", None))
        self.label_4.setText(_translate("Form", "Time (s) Since Start:", None))
        self.label.setText(_translate("Form", "Current Scan Progress:", None))
        self.label_2.setText(_translate("Form", "Total Experiment Progress:", None))
        self.total_experiment_progressbar.setFormat(_translate("Form", "%p%", None))
        self.current_scan_progressbar.setFormat(_translate("Form", "%p", None))
        self.label_3.setText(_translate("Form", "Current Scan", None))
        self.abort_button.setText(_translate("Form", "Abort Experiment", None))
        self.begin_button.setText(_translate("Form", "Begin Experiment", None))
        self.data_button.setText(_translate("Form", "Data Log ...", None))
        self.connect_button.setText(_translate("Form", "Connect", None))
        self.label_7.setText(_translate("Form", "SR430 Device ID:", None))
        self.label_6.setText(_translate("Form", "HP6033A Device ID:", None))
        self.label_5.setText(_translate("Form", "Host Name:", None))
        self.host_name_combobox.setItemText(0, _translate("Form", "planetexpress", None))
        self.host_name_combobox.setItemText(1, _translate("Form", "flexo", None))
        self.host_name_combobox.setItemText(2, _translate("Form", "bender", None))
        self.host_name_combobox.setItemText(3, _translate("Form", "calculon", None))
        self.label_8.setText(_translate("Form", "Mass Spectrum Experiment II", None))

